showwin/speedtest-go

docs/release.md

add release note for me

---

speedtest.go

Release v1.0.5

---

.gitignore
README.md
docs/saving_mode_experimental_result.md
speedtest.go
speedtest/request.go

ref: https://github.com/showwin/speedtest-go/issues/23

add --saving-mode to reduce memory usage

---

README.md

add cbergoon to contributors

---

speedtest.go

* added `--saving-mode` option.

Release v1.1.0

---

speedtest.go

* https://github.com/showwin/speedtest-go/pull/28
* Fix http request error handle in Go library

Release v1.1.1

---

speedtest.go

follow up of https://github.com/showwin/speedtest-go/pull/38

[fix] jsonOuput -> jsonOutput

---

speedtest.go

* https://github.com/showwin/speedtest-go/pull/38
* https://github.com/showwin/speedtest-go/pull/41
* https://github.com/showwin/speedtest-go/pull/42
* https://github.com/showwin/speedtest-go/pull/46
* https://github.com/showwin/speedtest-go/pull/47
* https://github.com/showwin/speedtest-go/pull/48

Release v1.1.3

---

speedtest.go

* https://github.com/showwin/speedtest-go/pull/52
* https://github.com/showwin/speedtest-go/pull/53
* https://github.com/showwin/speedtest-go/pull/56
* https://github.com/showwin/speedtest-go/pull/58

Release v1.1.4

---

speedtest/server.go

minor fix that are came from merging #62 and #63

fix conflict from #62 and #63

---

speedtest.go

This release includes
* https://github.com/showwin/speedtest-go/pull/62
* https://github.com/showwin/speedtest-go/pull/63
* https://github.com/showwin/speedtest-go/pull/66

Release v1.1.5

---

README.md

FetchServerList was renamed FetchServers in commit 83b44c5b4d6829dd4c985141cb786d20646626d2
Update API Usage example to reflect change

Update API Usage example to call FetchServers

---

speedtest.go

This release includes:
* https://github.com/showwin/speedtest-go/pull/75
* https://github.com/showwin/speedtest-go/pull/69
* https://github.com/showwin/speedtest-go/pull/76

Release v1.2.0

---

README.md

Thankfully, many people have contributed and it takes some time to keep updating the list so I start relying on GitHub.

Stop updating contributors

---

speedtest.go

This release contains:
* https://github.com/showwin/speedtest-go/pull/80
* https://github.com/showwin/speedtest-go/pull/81

Release v1.2.1

---

docs/release.md

update the way to release new version

---

speedtest/speedtest.go

Fix:
* https://github.com/showwin/speedtest-go/pull/83
* https://github.com/showwin/speedtest-go/pull/85
* https://github.com/showwin/speedtest-go/pull/87
Breaking changes:
* https://github.com/showwin/speedtest-go/pull/84

Release v1.3.0

---

speedtest/request.go

fix: negative up-rate caused by main test skipping

---

speedtest/request.go
speedtest/utils.go

change: use a custom reader to allocate less memory when uploading

---

speedtest/speedtest.go

Improvement:
* https://github.com/showwin/speedtest-go/pull/90
Fix:
* https://github.com/showwin/speedtest-go/pull/89
* https://github.com/showwin/speedtest-go/pull/87

Release v1.3.1

---

README.md
example/main.go
go.mod
go.sum
speedtest.go
speedtest/data_manager.go
speedtest/data_manager_test.go
speedtest/request.go
speedtest/request_test.go
speedtest/server.go
speedtest/server_test.go
speedtest/speedtest.go
speedtest/speedtest_test.go

Unify the speedtext context of fetch servers and custom servers.

chore: replace doer with speedtest context

---

README.md
speedtest.go
speedtest/data_manager.go
speedtest/data_manager_test.go
speedtest/debug.go
speedtest/location.go
speedtest/request.go
speedtest/request_test.go
speedtest/server.go
speedtest/speedtest.go
speedtest/speedtest_test.go
speedtest/user.go

feat: ping automatic selection, debug mode and calc-method fixing

---

README.md
example/main.go
speedtest.go
speedtest/request.go
speedtest/speedtest.go

Breaking: API  Changes: 
func (s *Server) MultiDownloadTestContext(ctx context.Context, servers Servers) error {}
func (s *Server) MultiUploadTestContext(ctx context.Context, servers Servers) error {}
func (s *Server) DownloadTest() error {}
func (s *Server) DownloadTestContext(ctx context.Context) error {}
func (s *Server) UploadTest() error {}
func (s *Server) UploadTestContext(ctx context.Context) error {}

change: savingmode

---

speedtest/debug.go
speedtest/speedtest.go

fix: remove unexpected use of io.discard

---

example/main.go
speedtest/server.go
speedtest/speedtest.go
speedtest/user.go

Related to #127 and  https://github.com/influxdata/telegraf/pull/13369

fix: remove the context dependency of FetchServers() and FetchUserInfo()

---

speedtest/server.go
speedtest/server_test.go
speedtest/speedtest.go

feat: add new api for getting the server by id

---

speedtest/speedtest.go

* https://github.com/showwin/speedtest-go/pull/144

Release v1.6.5

---

speedtest.go
speedtest/request.go
speedtest/request_test.go

speedtest-go v1.6.7 @showwin
✓ ISP: ******
✓ Found 20 Public Servers
✓ Test Server: ******
✓ Latency: 24.598265ms Jitter: 3.216308ms Min: 19.59715ms Max: 30.65055ms
✓ Download: 13.53Mbps (used: 16.13MB) (latency: 163ms jitter: 53ms min: 48ms max: 250ms)
✓ Upload: 31.22Mbps (used: 37.22MB) (latency: 185ms jitter: 59ms min: 92ms max: 341ms)

feat: support dl/ul and ping at the same time

---

speedtest.go
speedtest/request.go

fix(icmp): drop all datagram which control type not zero

---

speedtest/request.go

Fix goroutines leak 

---

speedtest/server_test.go

fix: TestFetchServerByID broken

---

speedtest/request.go
speedtest/server.go

Fixes the path for latency.txt and improves general URL handling.

Improve URL handling

---

speedtest/server.go
speedtest/server_test.go

fix: remove old testcase and use a compatible splicing method

---

speedtest/request.go

chore: fix lint error

---

README.md
speedtest/speedtest.go

Release 1.7.1

---

README.md
speedtest/speedtest.go
speedtest/transport/udp.go

fix untyped int constant overflows: nounce

Release v1.7.2

---

speedtest/unit.go

func (r ByteRate) Mbps() float64
func (r ByteRate) Gbps() float64

chore: add Mbps and Gbps for unit

---

README.md
speedtest/speedtest.go

Release v1.7.8

---

speedtest/data_manager.go
speedtest/request.go

fix: keepalive state broken

---

README.md
speedtest/speedtest.go

Release v1.7.9
