showwin/speedtest-go

- server.go
if `www.speedtes.net/speedtest-servers-static.php` doesn't respond the server list,
Maybe `speedtest-go` should try `c.speedtest.net/speedtest-servers-static.php` like [speedtest-cli](https://github.com/sivel/speedtest-cli/blob/7b09d8759fcbbda8a71aa49a4eaa825581b07439/speedtest_cli.py#L419)
> Add fail-safe

- .gitignore
- go.mod
- go.sum
goreleaser requires go mod at https://github.com/showwin/speedtest-go/runs/1418958144?check_suite_focus=true
> using go mod

- README.md
Looks like the functions were updated to expect `savingMode bool` and the API example wasn't updated. I've set savingMode to `false` in the example.
> Fix API example in README

- speedtest/request.go
Fixed weight is used when testing upload speed. So fix it to use dynamic weight, because the testing execution time would be too long with narrow bandwidth.
> Using dynamic weight when uploading test

- speedtest/request.go
@showwin  I found a bug as below:
```
Target Server: [4884]   211.28km Fuzhou (China) by China Unicom FuJian
2021/03/31 11:55:06 s.URL: http://upload1.testspeed.kaopuyun.com:8080/speedtest/upload.php
2021/03/31 11:55:06 Get http://latency.txt: dial tcp: lookup latency.txt on 192.168.1.1:53: no such host
```
> - bugfix for request.go

- .gitignore
- go.mod
- go.sum
- speedtest/request.go
- speedtest/server.go
- speedtest/user.go
Thanks for this useful library, you saved me a bunch of time recently 😄 
This PR adds support for the [`context`](https://golang.org/pkg/context/) package for any methods that do I/O.
The original methods remain, but there are new methods added to handle contexts. This is the same approach taken by the `sql` package.
> Add support for the context package

- speedtest/request.go
- speedtest/request_test.go
goal: 
before: 
```
Latency: 14.69305ms
Download: 258.97 Mbit/s
Upload: 271.74 Mbit/s
```
after: 
```
Latency: 12.8785ms
Download: 306.26 Mbit/s
Upload: 277.88 Mbit/s
```
still low accuracy... 🤔
> [add] workload option for high speed env

- .github/workflows/release.yml
> use go 1.16 for release build

- speedtest.go
Fatal is equivalent to Print() followed by a call to os.Exit(1).
https://pkg.go.dev/log#Fatal
> [-] os.Exit is redundant

- speedtest/request.go
- speedtest/request_test.go
See https://github.com/showwin/speedtest-go/pull/41#issuecomment-893234635 for detail - the previous alterations made in https://github.com/showwin/speedtest-go/pull/44 made it impossible to call the context-observing versions of the `DownloadTest` and `UploadTest` functions in the same was as the context-free versions.
> Alter exposed functions that take contexts

- speedtest/request.go
- speedtest/request_test.go
- speedtest/server.go
- speedtest/server_test.go
- speedtest/speedtest.go
- speedtest/speedtest_test.go
- speedtest/user.go
- speedtest/user_test.go
Thanks for useful package! 🤝 
We need to bench multiple proxies concurrently. It's not possible in current implementation without dirty hacks. 
So, instead of use global `http.DefaultClient` we add struct `speedtest.Speedtest` which contains it in itself and allows you to redefine. Backward compatibility is maintained, we use method like in `math/rand` package.
> Add speedtest struct which contains the global variables used

- speedtest.go
- speedtest/server.go
- speedtest/server_test.go
Switched to using `https://www.speedtest.net/api/js/servers?engine=js&limit=10` as primary server list request.
This fixes #50.
> use /api/js endpoint as new primary endpoint for server list fetching

- speedtest/request.go
This change will fix https://github.com/showwin/speedtest-go/issues/57.
This problem can be occurred when download warm-up process finished too fast.
`s.Latency` value is calculated when we get a server information, it means this value is not related to the warm-up process.
so `sTime.Add(s.Latency)` can be larger than `fTime` [here](https://github.com/showwin/speedtest-go/compare/fix_minus_speed?expand=1#diff-0ce50d5f1d88fb9df796031f74be6eb59c03f1469f49c84e4b5838ebcd6a01dbR58) if the latency is faster during warm-up than during getting the server information and download process finished too fast.
Then if `wuSpeed` is negative value, speedtest-go skip the main process to measure download speed [here](https://github.com/showwin/speedtest-go/blob/fix_minus_speed/speedtest/request.go#L85-L87) …
> fix: speed value can be negative if the bandwidth is large

- speedtest/request.go
Since Golang 1.16, `ioutil.Discard` has been merged into `io` package. More info at [here](https://go-review.googlesource.com/c/go/+/263141).
> fix: change ioutil.Discard to io.Discard

- README.md
- speedtest.go
- speedtest/location.go
- speedtest/server.go
- speedtest/user.go
- speedtest/user_test.go
When using the new api, we can easily change the current location to get a different server list.
implement  #2 Use map to pre-mark each location
usage:
Select the best server under the current label for testing
~~`.\speedtest-go.exe --world=beijing`~~
`.\speedtest-go.exe --city=tokyo`
List servers under the current label
~~`.\speedtest-go.exe --world=paris -l`~~
`.\speedtest-go.exe --city=tokyo -l`
> Add --world option and support test somewhere with predefined location

- speedtest/server.go
- speedtest/user.go
Hi,
I do not know Go and never work with it.
It is probably not the best way to fix the problem. 
Having a central way that always set User-Agent will be probably better.
Nevertheless, with this change, tests are greens otherwise that are failing.
```
go test -v
=== RUN   TestDownloadTestContext
--- PASS: TestDownloadTestContext (0.61s)
=== RUN   TestDownloadTestContextSavingMode
--- PASS: TestDownloadTestContextSavingMode (0.61s)
=== RUN   TestUploadTestContext
--- PASS: TestUploadTestContext (0.62s)
=== RUN   TestUploadTestContextSavingMode
--- PASS: TestUploadTestContextSavingMode (0.61s)
=== RUN   TestFetchServerList
--- PASS: TestFetchServerList (0.32s)
=== RUN   TestDistance
--- PASS: TestDistance (0.00s)
=== RUN   TestFindServer
--- PASS: TestFindServer (0.00s)
=== RUN   TestNew …
```
> Add User-Agent to http request to avoid request error in some cases.

- .goreleaser.yml
Due to https://github.com/showwin/speedtest-go/actions/runs/3426179465/jobs/5771140354 error
> disable arm64 build temporally

- .goreleaser.yml
This commit resolves the the issue raised in #81, by specifically ignoring the `windows/arm64` pair, so that `linux/arm64` can continue built. It looks like https://github.com/goreleaser/goreleaser/issues/142 raised this already with the `goreleaser` folks, there was a prior PR to skip unsupported `goos`/`goarch` pairs, but it never got merged 😞. To get an arm64 release, you'll probably need to create a new release.
**Testing**
To test this, I tagged and ran goreleaser locally. Not this PR doesn't actually include the `1.2,2` release tag, I just created that locally for this test.
```bash
~/speedtest-go ❯❯❯ git tag 1.2.2                                                                                                     ✘ 1
~/speedtest-go ❯❯❯ goreleaser build
• starting build...
• loading …
```
> [fix] Ignore windows/arm64 pair to re-enable linux/arm64 releases

- speedtest.go
- speedtest/server.go
- speedtest/speedtest.go
- speedtest/speedtest_test.go
- speedtest/user.go
This PR sets a custom user-agent on all requests set by the speedtest library: `showwin/speedtest-go <version>`. This UserAgent can be overridden with a new `Option`, `WithUserAgent`. This `WithUserAgent` option is just a convenience function -- it wraps the transport on the client's Doer to add a `user-agent` to all requests. As such, you can use it with a custom Doer if you want (as long as you pass the custom doer first), or you can just implement your own User-Agent on the doer you pass in.
I thought this might be a little nicer way to handle user-agents, but this PR is definitely a little opinionated, glad to adjust or close, just lmk :-) 
New Unit Tests are added to test the user-agent behavior, and all tests pass:
```
~/speedtest-go ❯❯❯ go test ./... -v
? …
```
> set custom user-agent on all requests

- speedtest/speedtest_test.go
> Evaluate the last code for golangci-lint

- README.md
- speedtest.go
- speedtest/speedtest.go
this patch add a proxy support for speedtest and all request traffic will pass through agent.
Usage:  
1. `./speedtest -s xxxx --proxy=socks://127.0.0.1:7890`
2. ~~`speedtest.WithProxy("http://127.0.0.1:7890")(speedtestClient)`~~`speedtest.WithUserConfig(&speedtest.UserConfig{Proxy: "http://127.0.0.1:7890"})(speedtestClient)` with code.
> feature: proxy support

- speedtest/request.go
- speedtest/request_test.go
- speedtest/server.go
- speedtest/server_test.go
In this PR I added a ping, download and upload duration. Plus one common function to measure all the things at once (one by one of course).
> feat: add download, upload, ping tests duration

- README.md
- speedtest.go
> feat: add --force-http-ping flag

- speedtest/data_manager.go
- speedtest/request.go
- speedtest/server.go
hide internal type params to avoid complex context of speedtest.xxxx.
> chore: hide internal type params

- speedtest/server.go
Remove Context field output in json.
> fix: hide redundant json content

- speedtest/data_manager.go
As stated on Ticker.Stop:
Stop does not close the channel, to prevent a concurrent goroutine
reading from the channel from seeing an erroneous "tick".
This sole fact prevents the goroutine from exiting, and in result, causes a leak that is especially problematic when the project is used through an API and not a CLI.
This particular bug is directly affecting the Telegraf's [Internet Speed Input Plugin](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/internet_speed/internet_speed.go), so this fix is only resolving the part relevant to the plugin. 
There are two more occurrences of this pattern:
https://github.com/showwin/speedtest-go/blob/320b5b755b5ecf42797de0910defe1fa064634ec/speedtest/data_manager.go#L103 https://github.com/showwin/speedtest-go/blob/320b5b755b5ecf42797d …
> fix: clean-up the rate sequence goroutines to avoid leaking

- speedtest.go
- speedtest/server.go
Related to #126 
Use the `FetchServerByID(id string)` to find a specific server.
> fix: specify servers with FetchServerByID()

- speedtest/data_manager.go
- speedtest/speedtest.go
> fix: unexpected signal kill on some linux releases

- README.md
- example/main.go
- speedtest.go
- speedtest/data_manager.go
- speedtest/data_manager_test.go
- speedtest/request_test.go
- speedtest/speedtest.go
> fix: incorrectly using the same manager

- speedtest.go
- speedtest/request.go
- speedtest/server.go
- speedtest/server_test.go
- speedtest/speedtest.go
May be related to #160 
Temporary fix #159
> fix(cli): std deviation with zero-length vector

- speedtest.go
> fix: cursor hidden after listing available servers

- README.md
- speedtest.go
- speedtest/speedtest.go
Add parameter "--dns-bind-source" to support binding source address for DNS request.
Related to #179
> feat: support dns request binding source

- speedtest/speedtest.go
The PR introduces a DialerControl property to allow a caller to execute syscalls on the socket before a connection is established.
Binding an IP via `Source` property is not always an option, in my case I am using a series of devices which get all the same IP and all have the same subnet: the only way to control which one has to be used is to bind the socket to a specific interface.
Here an example of the code
```
interfaceName := "XYZ"
speedTestClient = speedtest.New(speedtest.WithUserConfig(&speedtest.UserConfig{
DialerControl: func(network, address string, conn syscall.RawConn) error {
var operr error
if err = conn.Control(func(fd uintptr) {
operr = syscall.SetsockoptString(int(fd), syscall.SOL_SOCKET, syscall.SO_BINDTODEVICE, interfaceName)
}); err != nil {
return err
}
if operr != …
```
> Expose a property to set Dialer.Control

- README.md
- speedtest.go
- speedtest/speedtest.go
> feat: add ua option for cli

- speedtest/request.go
This PR improves the behaviour of how the context is handled in HTTPPing.
Currently, if a context is cancelled, the HTTPPing will keep trying executing the requests, failing them, to return at the end a timeout error, therefore misreporting the reason for which the requests are actually failing.
On top of this, if a number of pings passed before the context got cancelled or the deadline was hit, the error will not be reported at all, making it hard for the caller to understand if the operation was succesful or not.
In my specific case I need to ensure that if I don't get a response within 30/60 seconds the speedtest terminates and reports the reason for the termination and in case it's a timeout it doesn't report general errors.
The PR ensure that if a context cancelled or a deadline hit, …
> Ensure that the context cancel and deadline hit are respected and the related errors properly propagated

- README.md
- example/main.go
- speedtest.go
- speedtest/data_manager.go
- speedtest/request.go
- speedtest/server.go
- speedtest/unit.go
- speedtest/unit_test.go
Related to #192 #158 #187 #182
> feat: support human-readable and auto-scaled rate units for output

- README.md
- speedtest/speedtest.go
> Release v1.7.3

- example/packet_loss/main.go
- speedtest.go
- speedtest/loss.go
- speedtest/transport/tcp.go
func (pla *PacketLossAnalyzer) RunMulti(hosts []string) (float64, error)
func (pla *PacketLossAnalyzer) RunMultiWithContext(ctx context.Context, hosts []string) (float64, error)
> feat(api): add RunMulti and RunMultiWithContext

- example/packet_loss/main.go
- speedtest/loss.go
- speedtest/transport/tcp.go
breaking change: 
from `func (pla *PacketLossAnalyzer) RunMulti(hosts []string) (float64, error) {`
to `func (pla *PacketLossAnalyzer) RunMulti(hosts []string) (*transport.PLoss, error) {`
from `func (pla *PacketLossAnalyzer) RunMultiWithContext(ctx context.Context, hosts []string) (float64, error) {`
to `func (pla *PacketLossAnalyzer) RunMultiWithContext(ctx context.Context, hosts []string) (*transport.PLoss, error) {`
> fix(api): unified packet loss interface

- speedtest/data_manager.go
- speedtest/request.go
> fix(api): hook all traffic after Write() for upload

- README.md
- speedtest/speedtest.go
> Release v1.7.7

- speedtest.go
- speedtest/data_manager.go
- speedtest/data_manager_test.go
- speedtest/server.go
Related to https://github.com/ledgerwatch/erigon/pull/11138 #223
> fix: data races

- .github/workflows/release.yml
> chore: bump workflows/release/go/version from 1.19.0 to 1.23.4
